language: node_js
sudo: true
before_install:
  - curl -s https://raw.githubusercontent.com/Intervox/node-webp/latest/bin/install_webp | sudo bash
node_js:
  - 0.10
  - 0.12
  - 4.0
after_script:
  - npm run coveralls
